version: "3"

volumes:
  mysql-data:
    driver: local
  mvn-deps:
    driver: local

services:
  server:
    image: openjdk:8-alpine
    volumes:
      - ./target:/usr/src/app
    working_dir: /usr/src/app
    command: java -cp dependency/mysql-connector-java-5.1.6.jar:classes br.ufscar.servidorpagamento.Main
    depends_on:
      - mvn
      - mysql

  client:
    image: openjdk:8-alpine
    volumes:
      - ./target:/usr/src/app
    working_dir: /usr/src/app
    command: java -cp dependency/mysql-connector-java-5.1.6.jar:classes br.ufscar.clientepagamento.Main
    depends_on:
      - server

  mysql:
    image: mysql
    volumes:
      - ./database/data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb

  mvn:
    image: maven:alpine
    entrypoint: mvn
    command: install
    volumes:
      - .:/usr/src/app
      - mvn-deps:/root/.m2
    working_dir: /usr/src/app
